services:
  - type: web
    name: tournament-ff-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        sync: false
      - key: GROUP_LINK
        value: https://chat.whatsapp.com/KrQtBtM3oxwE0znHffPVFc?mode=gi_t
      - key: ADMIN_USERNAME
        value: SWADHIN MANDAL
      - key: ADMIN_PASSWORD
        sync: false
